### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Offynotar** [Baseult/Coloraimbot-CSharp#6]
Once you have put in the code in visual studio what do you do

**Comment by foxy17** [comment]
Alt-f4

**Comment by Offynotar** [comment]
?

**Comment by pozhiloy-enotik** [comment]
> 
> 
> Alt-f4

Stop spamming please, your squeaky voice won't change anything. Actually, this cheat doesn't work

**Comment by Offynotar** [comment]
stfu
