### ISSUE TITLE
Only work outside the game! Is it outdated?

### ISSUE THREAD

**Issue by Jonanthandx** [Baseult/Coloraimbot-CSharp#7]
The color ESP box is showing ingame but the others like aimbot and RCS just working outside the game( I setted valorant to windowed full screen).

**Comment by gsaucechrist31** [comment]
> The color ESP box is showing ingame but the others like aimbot and RCS just working outside the game( I setted valorant to windowed full screen).

Hi Jonanthandx, can you please tell me how to use this?

**Comment by Jonanthandx** [comment]
It's outdated I think. Nothing useful for now ==

**Comment by SebiTalent04** [comment]
yes it is outdated. also detectable and banable.

**Comment by oden228** [comment]
Baseult.. is it detected? I just want to use esp ..
